version: '3.8'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./src:/app/src
  #     - ./package.json:/app/package.json
  #     - /app/node_modules
  #   command: npm run start:dev

  # db:
  #   image: postgres:latest
  #   container_name: scanquiz_db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=scanquiz
  #     - POSTGRES_PASSWORD=scanquiz
  #     - POSTGRES_DB=scanquiz
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: scanquiz_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  bull-board:
    image: deadly0/bull-board
    container_name: scanquiz_bull_board
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

volumes:
  # postgres_data:
  redis_data: