version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scanquiz_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: scanquiz_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=scanquiz
      - POSTGRES_PASSWORD=scanquiz
      - POSTGRES_DB=scanquiz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: