services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - /app/node_modules
    command: npm run start:dev

  redis:
    image: redis:alpine
    container_name: scanquiz_redis
    restart: unless-stopped
    ports:
      - "6379:6379"